openapi: 3.0.0
info:
  title: Todo App Tasks API
  version: 1.0.0
  description: API for managing user tasks in the Todo application

paths:
  /api/tasks:
    get:
      summary: Get user's tasks
      description: Retrieves all tasks belonging to the authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '500':
          description: Internal server error
    post:
      summary: Create a new task
      description: Creates a new task for the authenticated user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  maxLength: 255
                  description: Task title
                description:
                  type: string
                  maxLength: 1000
                  description: Optional task description
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized - invalid or expired token
        '500':
          description: Internal server error

  /api/tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieves a specific task by ID if it belongs to the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - task does not belong to user
        '404':
          description: Task not found
        '500':
          description: Internal server error
    put:
      summary: Update a task
      description: Updates an existing task if it belongs to the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 255
                  description: Task title
                description:
                  type: string
                  maxLength: 1000
                  description: Task description
                is_completed:
                  type: boolean
                  description: Task completion status
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - task does not belong to user
        '404':
          description: Task not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a task
      description: Deletes a task if it belongs to the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - task does not belong to user
        '404':
          description: Task not found
        '500':
          description: Internal server error

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        title:
          type: string
          maxLength: 255
          description: Task title
        description:
          type: string
          maxLength: 1000
          description: Optional task description
        is_completed:
          type: boolean
          description: Task completion status
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns the task
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
      required:
        - id
        - title
        - is_completed
        - user_id
        - created_at
        - updated_at