"""
Occurrence Generator Service
"""
from datetime import datetime
from typing import Dict, Any
from .rrule_parser import get_next_occurrence

class OccurrenceGenerator:
    def __init__(self):
        pass
    
    async def generate_next_occurrence(self, task_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate the next occurrence of a recurring task.
        """
        if not task_data.get('is_recurring'):
            raise ValueError("Task is not recurring")
            
        recurrence_rule = task_data.get('recurrence_rule')
        if not recurrence_rule:
            raise ValueError("Recurrence rule is required for recurring tasks")
            
        last_completion_date = datetime.fromisoformat(task_data.get('completed_at')) if task_data.get('completed_at') else datetime.utcnow()
        
        next_occurrence_date = get_next_occurrence(recurrence_rule, last_completion_date)
        if not next_occurrence_date:
            raise ValueError("Could not determine next occurrence date")
            
        # Create new task with next occurrence date
        new_task = task_data.copy()
        new_task['id'] = None  # Will be generated by DB
        new_task['created_at'] = datetime.utcnow().isoformat()
        new_task['completed_at'] = None
        new_task['due_at'] = next_occurrence_date.isoformat() if next_occurrence_date else None
        
        return new_task