#!/bin/bash
# Quick Cloud Deployment Setup

echo "==========================================================="
echo "Todo App Cloud Deployment Setup"
echo "==========================================================="
echo ""
echo "This script outlines the steps to deploy the Todo App to cloud"
echo "Choose your cloud provider:"
echo ""
echo "1) AWS EKS"
echo "2) Google Cloud GKE" 
echo "3) Microsoft Azure AKS"
echo "4) DigitalOcean Kubernetes"
echo "5) Just show me the deployment commands"
echo ""
read -p "Enter your choice (1-5): " choice

case $choice in
  1)
    echo ""
    echo "AWS EKS Deployment Steps:"
    echo "1. Create EKS cluster:"
    echo "   eksctl create cluster \\"
    echo "     --name todo-app-cluster \\"
    echo "     --version 1.28 \\"
    echo "     --region us-west-2 \\"
    echo "     --nodegroup-name standard-workers \\"
    echo "     --node-type t3.medium \\"
    echo "     --nodes 3 \\"
    echo "     --nodes-min 1 \\"
    echo "     --nodes-max 10 \\"
    echo "     --managed"
    echo ""
    echo "2. Configure kubectl:"
    echo "   aws eks update-kubeconfig --region us-west-2 --name todo-app-cluster"
    echo ""
    ;;
  2)
    echo ""
    echo "Google Cloud GKE Deployment Steps:"
    echo "1. Create GKE cluster:"
    echo "   gcloud container clusters create todo-app-cluster \\"
    echo "     --zone us-central1-a \\"
    echo "     --num-nodes 3 \\"
    echo "     --enable-autoscaling \\"
    echo "     --min-nodes 1 \\"
    echo "     --max-nodes 10 \\"
    echo "     --machine-type e2-standard-2"
    echo ""
    echo "2. Configure kubectl:"
    echo "   gcloud container clusters get-credentials todo-app-cluster --zone us-central1-a"
    echo ""
    ;;
  3)
    echo ""
    echo "Microsoft Azure AKS Deployment Steps:"
    echo "1. Create resource group:"
    echo "   az group create --name todo-app-rg --location eastus"
    echo ""
    echo "2. Create AKS cluster:"
    echo "   az aks create \\"
    echo "     --resource-group todo-app-rg \\"
    echo "     --name todo-app-cluster \\"
    echo "     --node-count 3 \\"
    echo "     --enable-auto-scaler \\"
    echo "     --min-count 1 \\"
    echo "     --max-count 10 \\"
    echo "     --generate-ssh-keys \\"
    echo "     --enable-managed-identity"
    echo ""
    echo "3. Configure kubectl:"
    echo "   az aks get-credentials --resource-group todo-app-rg --name todo-app-cluster"
    echo ""
    ;;
  4)
    echo ""
    echo "DigitalOcean Kubernetes Deployment Steps:"
    echo "1. Create cluster:"
    echo "   doctl kubernetes cluster create todo-app-cluster --region sfo3 --count 3 --size s-2vcpu-4gb"
    echo ""
    echo "2. Configure kubectl:"
    echo "   doctl kubernetes cluster kubeconfig save todo-app-cluster"
    echo ""
    ;;
  5)
    echo ""
    echo "Deployment Commands (after setting up cloud cluster):"
    echo ""
    echo "# 1. Build and push Docker images to your container registry"
    echo "docker build -t <your-registry>/todo-frontend:2.0.0-cloud ./frontend"
    echo "docker push <your-registry>/todo-frontend:2.0.0-cloud"
    echo ""
    echo "docker build -t <your-registry>/todo-backend:2.0.0-cloud ./backend"
    echo "docker push <your-registry>/todo-backend:2.0.0-cloud"
    echo ""
    echo "docker build -t <your-registry>/todo-recurring-task:2.0.0-cloud ./services/recurring-task"
    echo "docker push <your-registry>/todo-recurring-task:2.0.0-cloud"
    echo ""
    echo "docker build -t <your-registry>/todo-reminder-service:2.0.0-cloud ./services/reminder-service"
    echo "docker push <your-registry>/todo-reminder-service:2.0.0-cloud"
    echo ""
    echo "# 2. Update values-cloud.yaml with your registry URLs"
    echo ""
    echo "# 3. Install Dapr"
    echo "helm repo add dapr https://dapr.github.io/helm-charts"
    echo "helm repo update"
    echo "helm upgrade --install dapr dapr/dapr --namespace dapr-system --create-namespace --wait"
    echo ""
    echo "# 4. Install Strimzi Kafka Operator"
    echo "kubectl create namespace kafka"
    echo "kubectl apply -f https://strimzi.io/install/latest?namespace=kafka"
    echo "kubectl wait --for=condition=Ready pod -l name=strimzi-cluster-operator -n kafka --timeout=300s"
    echo ""
    echo "# 5. Deploy Kafka cluster"
    echo "kubectl apply -f k8s/kafka/kafka-cluster.yaml"
    echo "kubectl wait --for=condition=Ready kafka/todo-kafka -n kafka --timeout=600s"
    echo ""
    echo "# 6. Deploy Kafka topics"
    echo "kubectl apply -f k8s/kafka/kafka-topics.yaml"
    echo ""
    echo "# 7. Install Redis"
    echo "helm repo add bitnami https://charts.bitnami.com/bitnami"
    echo "helm repo update"
    echo "helm upgrade --install redis bitnami/redis --namespace todo-app [configuration options]"
    echo ""
    echo "# 8. Deploy the application"
    echo "helm dependency update ./charts/todo-app"
    echo "helm upgrade --install todo-app ./charts/todo-app \\"
    echo "  --namespace todo-app \\"
    echo "  --values ./charts/todo-app/values-cloud.yaml \\"
    echo "  --create-namespace \\"
    echo "  --wait"
    echo ""
    ;;
  *)
    echo "Invalid choice. Please run the script again and select 1-5."
    exit 1
    ;;
esac

echo "For complete instructions, see:"
echo "- DEPLOYMENT_GUIDE.md"
echo "- CLOUD_SETUP_GUIDE.md"
echo ""
echo "Remember to update the values-cloud.yaml file with your container registry URLs"
echo "before deploying to the cloud!"